//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------





namespace testNo3.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        //[global::System.Configuration.DefaultSettingValueAttribute("server=192.168.1.3;user id=smsadmin; password=SmsEonbotz2016!;database=bseddb;port=3306")]
        //[global::System.Configuration.DefaultSettingValueAttribute("server=localhost;user id=root; password=;database=smsdbv2;port=3306")]
        //[global::System.Configuration.DefaultSettingValueAttribute("server=192.168.1.3;user id=smsadmin; password=SmsEonbotz2016!;database=smsdbv2;port=3306")]
        //[global::System.Configuration.DefaultSettingValueAttribute("server=192.168.1.9;user id=Randel; password=RandelEonbotz2021;database=smsdbv2;port=3306;SSL Mode=None")]
        ///== developer 
        [global::System.Configuration.DefaultSettingValueAttribute("server=192.168.1.8;user id=Randel; password=RandelEonbotz2021;database=smsdbv2;port=3306;SSL Mode=None")]
        // ==== Dr P ====
        // [global::System.Configuration.DefaultSettingValueAttribute("server=192.168.1.3;user id=smsadmin; password=SmsEonbotz2016!;database=smsdbv2;port=3306;SSL Mode=None")]
        public string smsdbConnectionString
        {
            get
            {
                return ((string)(this["smsdbConnectionString"]));
            }
        }
    }
}
